spring.application.name=moneymoney

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/moneymoney
spring.datasource.username=postgres
spring.datasource.password=adminLocal
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
# 256-bit key generated for demo purposes
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
